CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# DYA Studio runtime pointing-device configuration
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=2048

# DYA Studio BLE profile / pairing management
CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y
